### PR TITLE
Chore: Update README links

### PR DESCRIPTION
**Pull request by marcoscaceres**
Note that this is not currently serving via gh pages yet.

### CODE REVIEW

**Comment by ricea** [comment]
Can we wait until it is serving before landing this?

**Comment by marcoscaceres** [comment]
Sure. Merge whenever you are ready:)

**Comment by ricea** [comment]
Do you know who I need to talk to about making it be served by github pages?

**Comment by marcoscaceres** [comment]
me :) Let me check the permissions... you should be able to control that.

**Comment by marcoscaceres** [comment]
Ok, made you admin. You should be able to control the branches now.

**Pull request merged**
