### PR TITLE
Do not allow trailing data for deflate-raw decompression

### PR DESCRIPTION
**Pull request by fhanau**
See #47. Looks like the updated Bikeshed version resulted in a pretty large diff – search for `BFINAL` to find the relevant change in the html file.

***
<a href="https://pr-preview.s3.amazonaws.com/fhanau/compression/pull/48.html" title="Last updated on Feb 27, 2023, 6:29 PM UTC (edf178b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/48/8e3b2c4...fhanau:edf178b.html" title="Last updated on Feb 27, 2023, 6:29 PM UTC (edf178b)">Diff</a>

### CODE REVIEW

**Review by ricea — APPROVED** [review]
lgtm

**Comment by ricea** [comment]
Sorry for the inconvenience, could you follow the IPR process as described at https://labs.w3.org/repo-manager/pr/id/WICG/compression/48 ?

**Comment by fhanau** [comment]
Looks like it would be difficult for me to complete the steps right now – can you make a pull request instead?

**Comment by ricea** [comment]
Understandable. I will make a PR.

**Comment by ricea** [comment]
I created a PR at #49. PTAL.

**Pull request closed without merging**
