### PR TITLE
Rename .pr-preview to .pr-preview.json

### PR DESCRIPTION
**Pull request by tobie**
Followup to #18

### CODE REVIEW

**Comment by domenic** [comment]
Wow, I'm so sorry for wasting folks time on this ^_^

**Comment by tobie** [comment]
You’re all good. I still owe you plenty.

**Comment by ricea** [comment]
@domenic How to fix the ipr check?

**Comment by domenic** [comment]
Click details and give that sketchy app write access to all your private GitHub repos... Or wait for @marcoscaceres to do it for us :)

**Comment by tobie** [comment]
Alternatively.m, close this PR and rename the file yourself. :D

**Comment by yoavweiss** [comment]
Marked as non substantive for IPR from ash-nazg.

**Pull request merged**
